apiVersion: v1
kind: Pod
metadata:
  name: sharedmem-pod
spec:
  containers:
  - name: writer
    image: gcc:latest
    command: ["sh", "-c", "g++ /src/producer.cpp -o /producer && /producer"]
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
  - name: reader
    image: gcc:latest
    command: ["sh", "-c", "g++ /src/consumer.cpp -o /consumer && sleep 5 && /consumer"]
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
